# Generated by Django 4.2.14 on 2024-07-23 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxparser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_position', models.DecimalField(decimal_places=0, max_digits=4)),
                ('y_position', models.DecimalField(decimal_places=0, max_digits=4)),
                ('key', models.CharField(max_length=200)),
                ('tax_form', models.CharField(max_length=200)),
                ('values', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaxFormValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_form', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TaxDocumentValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.TextField(blank=True, null=True)),
                ('key_locations', models.TextField(blank=True, null=True)),
                ('raw_ocr', models.TextField(blank=True, null=True)),
                ('document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxparser.pdfdocument')),
            ],
        ),
    ]
