# Generated by Django 4.2.14 on 2024-07-23 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxparser', '0002_taxdocument_taxformvalues_taxdocumentvalues'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxdocumentvalues',
            name='id',
        ),
        migrations.AlterField(
            model_name='taxdocumentvalues',
            name='document_id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
