# Generated by Django 4.2.14 on 2024-07-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxparser', '0004_taxdocument_tax_line_alter_taxdocument_values_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxformvalues',
            name='tax_line',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
