# Generated by Django 4.2.14 on 2024-07-23 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxparser', '0005_taxformvalues_tax_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='tax_form',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
