# Generated by Django 4.2.14 on 2024-07-23 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxparser', '0006_pdfdocument_tax_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxForm1040',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxparser.pdfdocument')),
            ],
        ),
    ]
