# Generated by Django 4.2.14 on 2024-07-23 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxparser', '0008_taxform1040_line_11_taxform1040_line_12_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxform1040',
            old_name='document_id',
            new_name='document',
        ),
    ]
