# Generated by Django 4.2.14 on 2024-07-23 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxparser', '0009_rename_document_id_taxform1040_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxform1040',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taxparser.pdfdocument'),
        ),
    ]
